# -*- coding: utf-8 -*-
"""Tableau Ödev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wG-o2yMZxFs9_1xubImy04Ebnt9QBXy0
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/covid_worldwide.xls.csv')
df.head()

df.replace("N/A", np.nan, inplace=True)

df_cleaned = df.dropna()

print(df_cleaned)

df_cleaned.to_csv("covid_cleaned.csv", index=False)